<FinanceScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: 20

        Label:
            text: "FINANCE"
            font_size: 28
            color: 0, 0, 0, 1

        Widget:

        Button:
            text: "RETOUR"
            background_color: 1, 0, 0, 1
            on_press: app.root.current = "main"